#!/bin/bash

set -eu

if [ "$#" -lt 1 ]; then
   echo "usage $0 <engine.cfg> <engine_ip>"
   exit 1
fi

engine_cfg=$1
engine_ip=$2

if [[ -z "$engine_ip" ]]; then
    engine_ip=`perl -nle ' print "$1" if m|stonegate/network/ipaddr string ([\d\.]+)|' $engine_cfg`
fi

scp $engine_cfg "root@$engine_ip:/data/config/base/engine.cfg"
ssh "root@$engine_ip" "sg-reconfigure --import; sg-contact-mgmt --auto"
